- CMakeLists.txt
This should make it easier for users to integrate S2 in projects that require static builds. The `BUILD_SHARED_LIBS` option is [idiomatic](https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html).
> Add shared/static build option.

- src/s2/util/gtl/btree.h
Since Windows doesn't have `ssize_t`, converting to the standardized `std::make_signed<size_t>::type` fixes compilation issues there.
> Remove platform-specific ssize_t from btree implementation.

- src/s2/util/gtl/btree.h
I think I had an `#undef small` in a previous PR, but it seems to have been lost along the way. Changing the name from `small` to `smaller` fixes the issue in a more portable way, and changing `large` to `larger` is just for consistency.
> Change some names to fix conflict with Windows macro.

- CMakeLists.txt
Currently using the provided cmake file always builds the examples. We include S2 in a larger project and we thought that it would be a good idea to make that optional via a flag
> Make building examples optional

- src/s2/s2builder_graph.cc
For some reason MSVC 2015 doesn't compile this without the class name
> Fix a windows compile error

- CONTRIBUTORS
- src/python/CMakeLists.txt
Fix the use of the deprecated swig_add_module in place of SWIG_ADD_LIBRARY.
Fix the installation location from ${prefix}/share/python/ to ${PYTHON_SITE_PACKAGES}/
Closes #6 
I've just signed the CLA.
Note: I'm not particularly strong with CMake, and used this as an excuse to get some more familiarity.
> Improve the installation of the Python bindings

- doc/examples/point_index.cc
- doc/examples/term_index.cc
- src/s2/base/commandlineflags.h
- src/s2/mutable_s2shape_index.cc
- src/s2/s2builder_test.cc
- src/s2/s2cell_union.cc
- src/s2/s2cell_union.h
- src/s2/s2cell_union_test.cc
- src/s2/s2debug.cc
- src/s2/s2debug.h
- src/s2/s2loop.cc
- src/s2/s2point_compression_test.cc
- src/s2/s2polygon.cc
- src/s2/s2predicates_test.cc
- src/s2/s2region_coverer_test.cc
- src/s2/s2region_term_indexer_test.cc
- src/s2/s2testing.cc
- src/s2/s2testing.h
The gflags macro names (`DEFINE_`) are also used by glog. If you have a setup that uses glog but not gflags, the `glog/logging.h` header will actually undefine these macros. This causes a very difficult-to-find error in S2. This PR changes the names of these macros to a library-specific name to avoid this issue. It follows the pattern of the logging macros.
> Use local macro names to avoid conflicts with gflags.

- src/python/pywraps2_test.py
- src/python/s2_common.i
- src/s2/s2cell_id.h
Declare `S2CellId::FromToken` with `std::string` instead of `string` to please SWIG.
Fixes #109 
Add tests for SWIG `S2CellId.FromToken`/`ToToken`.
> SWIG-wrap only S2CellId::FromToken(const string&)

- src/s2/s2region_coverer.cc
- src/s2/s2region_coverer.h
Inspired by #85, which reports a gcc ubsan violation in `AddCandidate`.
I was not able to reproduce with `-fsanitize=undefined` but the current code
does look suspicious to me.
Current code:
```
Candidate* candidate = static_cast<Candidate*>(
::operator new(sizeof(Candidate) + children_size));
```
However, the `Candidate` constructor is never called, and `Candidate` is not
trivially constructible.  Candidate contains `S2Cell`, which contains
`R1Interval`, which is not trivially constructible.
Add `Candidate::operator new` with an extra arg of `max_children`;
this delegates to `::operator new`.  Similarly add `Candidate::operator delete`.
Move the `Candidate` initialization logic to a constructor.
> Add operator new/delete and ctor for Candidate

- .travis.yml
With some luck, this will also get us a newer swig version.
> travis: change osx_image from xcode8.3 to xcode12

- CMakeLists.txt
- README.md
- src/python/CMakeLists.txt
This should help solve problems where s2's SWIG module was build with
Python2, but users try to use Python3.
Python2 has been sunsetted as of 2020-01-01.
Increases required CMake version from 3.5 (released 2016-03) to 3.12
(released 2018-07).
> Require Python3

- src/s2/s2builderutil_lax_polygon_layer_test.cc
The cases are exhaustive, and this is not possible, but apparently
some compilers don't realize that and emit a warning.
Fixes #114
> ToString: LOG(FATAL) for unhandled value

- src/python/pywraps2_test.py
- src/python/s2_common.i
Update `__eq__` and `__ne__` for `S2Loop`, `S2Polyline`, and `S2Polygon`.
`==` in Python is expected to be value comparison.
Fixes #118
> Make == in python use Equals

- src/python/s2.i
Try to be forward-compatible with use of `<cstdint>` types, e.g.
`int64 -> std::uint64_t`.  Adding the include now should make
subsequent merges easier and pass travis-ci with fewer SWIG changes /
less SWIG knowledge.
> Include stdint.i in s2.i (SWIG)

- src/python/CMakeLists.txt
This should have been part of #128.
swig_add_module has been deprecated since CMake 3.8; we now require 3.12.
> python/CMakeLists.txt: Use swig_add_library

- src/python/pywraps2_test.py
- src/python/s2_common.i
This exposes `S2CellId::AppendAllNeighbors` to Python code as `S2CellId.GetAllNeighbors`:
```python
>>> import pywraps2 as s2
>>> p = s2.S2CellId.FromToken('6aa759')
>>> ','.join(_.ToToken() for _ in p.GetAllNeighbors(p.level()))
'2ab353,2ab34b,2ab34d,6aa75b,6aa757,6aa75f,6aa751,6aa75d'
```
I renamed this because "Append" doesn't make sense – SWIG is configured to convert passing a (mutable) output `std::vector` by reference into returning an immutable `tuple`.
This was exposed in the API before 13ab3fc4 removed all members by default.
> Expose S2CellId::AppendAllNeighbors in Python (as GetAllNeighbors)

- src/s2/s2polygon.cc
This was declared, but accidentally not defined.
Reimplement `InitToSnapped(..., level)` using the `SnapFunction` overload.
> Add S2Polygon::InitToSnapped(..., SnapFunction)

- CMakeLists.txt
On Linux systems, libraries need to be installed with attached version
information so other packages can depend on specific versions and make
sure they don't compile against a version they're not compatible with
This change installs libs2.so.0.10.0 with appropriate
symlinks as libs2.so.0 and libs2.so.
Do note that for new future versions, the version in CMakeLists.txt will have
to be updated as well
> CMake: add version information to the library

- AUTHORS
- CONTRIBUTORS
- doc/examples/term_index.py
- src/python/pywraps2_test.py
- src/python/s2.i
- src/python/s2_common.i
* Make it possible to follow the _Indexing for Search_ and _Querying for Search_ sections in the [Quickstart guide](https://s2geometry.io/devguide/cpp/quickstart#indexing-for-search) from Python.
* Primarily expand the Python bindings to include `S2RegionTermIndexer`
* And related changes for testing
* Port the `term_index.cc` example to Python as well for good measure.
* Add some `repr()` methods
Fixes #84
> Expand Python Bindings to include S2RegionTermIndexer

- .travis.yml
This is now timing out, causing all builds to fail.
> Remove xcode 10 from travis config

- src/s2/third_party/absl/base/internal/unaligned_access.h
For some reason this was `uint64`, which fails on aarch64, but not
elsewhere.
Fixes #165.
> Use uint64_t in absl/.../unaligned_access.h

- src/s2/util/gtl/compact_array.h
- src/s2/util/gtl/densehashtable.h
This is deprecated in C++17 and has been removed in C++20.
Use std::allocator_traits::rebind_alloc instead.
https://en.cppreference.com/w/cpp/memory/allocator
https://en.cppreference.com/w/cpp/memory/allocator_traits
Fixes #173.
> Remove use of std::allocator::rebind

- src/s2/third_party/absl/container/fixed_array.h
- src/s2/third_party/absl/container/inlined_vector.h
- src/s2/util/gtl/densehashtable.h
std::allocator::pointer, reference, max_size, etc. were deleted
in C++20.  Uses of rebind have already been removed from s2geometry.
https://en.cppreference.com/w/cpp/memory/allocator
https://en.cppreference.com/w/cpp/memory/allocator_traits
Fixes #173.
> Remove use of deleted std::allocator members

- src/s2/encoded_uint_vector_test.cc
This small change fix compilation error for 32-bit target.
And all checks from the `encoded_uint_vector_test` is passed for this case too.
> Allow encoded_uint_vector_test for 32-bit target

- src/s2/base/port.h
Tested for 32bit and 64bit targets via [MSYS2](https://www.msys2.org/) distro on `Windows`.
Similar PR #88.
> Add MinGW port

- src/s2/util/math/exactfloat/exactfloat.cc
Suggested changes fix compilation error with `OpenSSL` >= 1.0 for 32bit target.
The algorithm is similar to what is currently being done in `BN_ext_set_uint64`, but in the opposite direction.
> Fix BN_ext_get_uint64 for OpenSSL >= 1.1 32bit

- .travis.yml
- CMakeLists.txt
- README.md
Add a flag to determine if we should install the Python interface, and add additional python3-dev dependency to the install instructions.
> Make python optional via flags

- src/s2/base/port.h
This will prevent conflicts with other symbols in the global namespace.
Remove `using std::string` among other global symbols.
> Remove unused portions of base/port.h.

- src/s2/util/math/exactfloat/exactfloat.cc
Somehow, on my system `uint64` from port.h and `uint64_t` are typedefs of two different 64-bit types, `unsigned long` and `unsigned long long`.
For the most part this difference would be invisible, however when passing by pointer the pointer must point to the correct type.
No functionality change.
> BN_num_bits takes a uint64_t*, so pass it one.

- src/s2/encoded_s2point_vector.cc
- src/s2/encoded_string_vector.cc
- src/s2/encoded_uint_vector.h
- src/s2/s2builderutil_get_snapped_winding_delta.cc
- src/s2/s2cap.cc
- src/s2/s2convex_hull_query.cc
- src/s2/s2edge_tessellator.cc
- src/s2/s2loop.cc
- src/s2/s2polyline.cc
These were spotted with `-Wdeprecated-declarations` in a clang build.
No functionality change.
> Fix usage of deprecated APIs.

- doc/examples/point_index.cc
- doc/examples/term_index.cc
- src/s2/encoded_s2cell_id_vector.cc
- src/s2/encoded_s2cell_id_vector_test.cc
- src/s2/encoded_string_vector.cc
- src/s2/encoded_uint_vector.h
- src/s2/r1interval.h
- src/s2/s2cell_id.h
- src/s2/s2centroids.cc
- src/s2/s2closest_cell_query_base.h
- src/s2/s2edge_crossings.h
- src/s2/s2edge_distances.h
- src/s2/s2edge_vector_shape_test.cc
- src/s2/s2lax_polyline_shape.cc
- src/s2/s2lax_polyline_shape.h
- src/s2/s2lax_polyline_shape_test.cc
- src/s2/s2loop.cc
- src/s2/s2loop_measures.cc
- src/s2/s2metrics.h
- src/s2/s2metrics_test.cc
- src/s2/s2point_vector_shape_test.cc
- src/s2/s2pointutil.h
- src/s2/s2polygon.h
- src/s2/s2region_term_indexer_test.cc
- src/s2/s2shape_index_region.h
- src/s2/s2text_format.cc
- src/s2/s2text_format.h
- src/s2/util/bits/bits.h
* EncodedS2CellIdVector: Detect invalid cell levels and return failure
* Use Decoder::skip(0) instead of deprecated ptr()
* Deprecate more functions
* Make S2LaxPolylineShape moveable
* Improve comments
> Update to latest google3 version

- CMakeLists.txt
In order to be able to compile with [clang-cl](https://clang.llvm.org/docs/UsersManual.html#clang-cl), test for [MSVC](https://cmake.org/cmake/help/latest/variable/MSVC.html) rather than WIN32; the former is true for MSVC-compatible compilers.
> Allow compiling with MSVC-compatible compilers, i.e. clang-cl

- src/s2/encoded_s2point_vector_test.cc
keeping it consisting with the rest of the file (recent commit https://github.com/google/s2geometry/commit/88ccc24fe04306ac380326cc1c5f78ce5e56f41a did the same to other instances)
> "lengths" to "offsets"

- src/s2/util/math/exactfloat/exactfloat.cc
```
/usr/bin/c++ -DS2_USE_GFLAGS -DS2_USE_GLOG -Ds2_EXPORTS -I/wrkdirs/usr/ports/graphics/s2/work/s2geometry-0.10.0/src -O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing   -mcpu=power7 -isystem /usr/local/include -std=c++11 -O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing   -mcpu=power7 -isystem /usr/local/include -std=c++11 -fPIC   -Wno-attributes -Wno-deprecated-declarations -pthread -std=c++11 -MD -MT CMakeFiles/s2.dir/src/s2/util/math/exactfloat/exactfloat.cc.o -MF CMakeFiles/s2.dir/src/s2/util/math/exactfloat/exactfloat.cc.o.d -o CMakeFiles/s2.dir/src/s2/util/math/exactfloat/exactfloat.cc.o -c /wrkdirs/usr/ports/graphics/s2/work/s2geometry-0.10.0/src/s2/util/math/exactfloat/exactfloat.cc …
```
> Fix build on big-endian architectures

- src/python/pywraps2_test.py
- src/python/s2_common.i
With this small change we can code something like this:
```python
import numpy as np
from pywraps2 import S2Cell, S2CellId
from matplotlib import pyplot as plt
def surf4face(f, l):
m = 2**l; m1 = m + 1; m2 = m - 1
k = range(0, 2**S2CellId.kMaxLevel, 2**(S2CellId.kMaxLevel - l))
x = np.empty((m1,m1)); y = np.empty((m1,m1)); z = np.empty((m1,m1));
for i in range(m):
for j in range(m):
c = S2Cell(S2CellId.FromFaceIJ(f, k[i], k[j]).parent(l))
v = c.GetVertex(0)
x[i][j] = v.x(); y[i][j] = v.y(); z[i][j] = v.z();
if i == m2:
v = c.GetVertex(1)
x[m][j] = v.x(); y[m][j] = v.y(); z[m][j] = v.z();
if j == m2:
v = c.GetVertex(3)
x[i][m] = v.x(); y[i][m] = v.y(); z[i][m] = v.z();
if i == m2 and j == m2:
v = c.GetVertex(2)
x[m][m] = v.x(); y[m][m] = v.y(); z[m][m] = v.z();
return (x, y, z)
fig = …
```
> python: Named component accessors for S2Point

- AUTHORS
- CONTRIBUTORS
- src/python/pywraps2_test.py
- src/python/s2_common.i
- src/s2/mutable_s2shape_index.h
- src/s2/s2boolean_operation.h
- src/s2/s2buffer_operation.h
Add S2::UpdateMinDistance, s2pred::OrderedCCW, S2::Interpolate,
S2Polygon::InitToUnion, some more of S2::S1ChordAngle, and a
method for retrieving the S2Point's underlying 3-vector.
> Expose more functionality via the SWIG wrapper

- CMakeLists.txt
The command line argument for setting the C++ standard to use is ignored. This change allows the default to remain 11 but allow for the user to override it.
Resolve #270
> Fix -DCMAKE_CXX_STANDARD ignored by CMakeLists

- README.md
#278 (ABI compatability and SOVERSION) asked questions about ABI stability.
Clarify that nothing is stable while we are on 0.x releases, but we will adhere to SemVer starting with 1.0.
> README.md: Add warning about API/ABI stability

- src/s2/util/gtl/compact_array.h
Also I think really correct code, should start with non zero capacity (so correct capacity can be seted in ctor)
> Fix undefined sanitizer issue in compact_array

- src/python/pywraps2_test.py
- src/python/s2_common.i
Python strings have an explicit length, not a terminating zero byte.
Before:
$ python
Python 3.10.8 (main, Oct 11 2022, 11:35:05) [GCC 11.3.0] on linux Type "help", "copyright", "credits" or "license" for more information.
>>> import pywraps2 as s2
>>> str(s2.S1Angle.Degrees(123))
'123.0000000\x00'
>>> str(s2.S2CellId(12345))
'0/000000000000000000000001200130\x00'
After:
$ python
Python 3.10.8 (main, Oct 11 2022, 11:35:05) [GCC 11.3.0] on linux Type "help", "copyright", "credits" or "license" for more information.
>>> import pywraps2 as s2
>>> str(s2.S1Angle.Degrees(123))
'123.0000000'
>>> str(s2.S2CellId(12345))
'0/000000000000000000000001200130'
> Remove trailing null from Python strings

- src/s2/base/logging.h
if no defined ABSL_MIN_LOG_LEVEL severity_ will be unused.
Because its header it's pretty inconvenient.
As an alternative solution will be make field under ifdef.
But in this case layout of class will be changed, so I don't know, is it valid for you, I decide to make more simple fix.
> Fix possible warning in header

- README.md
- pyproject.toml
- setup.cfg
- setup.py
- src/python/CMakeLists.txt
- src/python/s2geometry_test.py
This pull request enables the creation of Python wheels via integration with CMake. This also changes the name of the Python library from `pywraps2` to the more ergonomic `s2geometry`.
> Add ability to create Python wheels

- src/s2/value_lexicon.h
Fix the build error like:
```
In file included from /usr/local/include/absl/hash/hash.h:85,
from /home/xxx/dev/s2geometry/src/s2/s2point.h:24,
from /home/xxx/dev/s2geometry/src/s2/value_lexicon_test.cc:28:
/usr/local/include/absl/hash/internal/hash.h:247:23: error: reference to 'hash_internal' is ambiguous
247 |   using is_hashable = absl::hash_internal::is_hashable<T>;
|                       ^~~~
In file included from /usr/local/include/absl/hash/internal/hash.h:49,
from /usr/local/include/absl/hash/hash.h:85,
from /home/xxx/dev/s2geometry/src/s2/s2point.h:24,
from /home/xxx/dev/s2geometry/src/s2/value_lexicon_test.cc:28:
/usr/local/include/absl/hash/internal/city.h:57:11: note: candidates are: 'namespace absl::lts_20230802::hash_internal { }'
57 | namespace hash_internal {
| …
```
> value_lexicon: Fix build with abseil LTS 2023-08-02

- CMakeLists.txt
In the use case of using s2geometry as a thirdparty library of a project, it's not needed to build S2 unit tests, but it's possible to use test utilities in src/s2/s2testing.
In this case, `s2testing` has to be exported, but unit tests are not necessary to build.
This patch adds an option `BUILD_TESTS` to decide whether to build S2 unit tests.
> Add a CMake option BUILD_TESTS to decide whether to build S2 unit tests

- src/s2/s1angle.cc
- src/s2/s2lax_polygon_shape.h
- src/s2/s2point.h
- src/s2/s2polygon.h
Attempting to fix some of the issues preventing compilation on Windows platforms, in order to then fix the vcpkg version to also support windows, and finally to fix a downstream consumer of s2geometry so it can use vcpkg for the dependency.
The `using Base::Base` technique to import the base class ctors doesn't appear to import the base class default ctor if it would otherwise be implicitly deleted (be the declaration of a non-default ctor in this case), at least on MSVC 2022.  See https://godbolt.org/z/EPnsMEq8v  Clang and GCC both seem to handle this OK.
`uint` isn't a primitive type or a guaranteed typedef in C++.  While Clang and GCC both appear to thread it as `unsigned int`, MSVC treats it as un unknown symbol.  Replacing it with `uint32_t` seems to do the trick.
> Fix several MSVC build issues

- CMakeLists.txt
- Config.cmake.in
The current vcpkg [version](https://github.com/microsoft/vcpkg/tree/master/ports/s2geometry) of s2geometry has to patch the [CMakeLists.txt](https://github.com/microsoft/vcpkg/blob/master/ports/s2geometry/CMakeLists.txt.patch) and generate a [Config.cmake.in](https://github.com/microsoft/vcpkg/blob/master/ports/s2geometry/Config.cmake.in.patch) file in order to create a modern CMake target file that can then be found by other packages via `find_package`.
Because this is a vcpkg addition, they mandate that this be placed in the `unofficial` namespace, in order to prevent any potential conflict with an eventual upstream config that might be introduced.  This PR introduces the upstream config so that it can be used by anyone who builds the package and so that the vcpkg version no longer …
> Add modern cmake config targets to s2geometry

- CMakeLists.txt
- Config.cmake.in
- src/s2/s2lax_polygon_shape.cc
Three minor changes related to my recent fixes for vcpkg and Windows builds
First, the namespace for the export target should be `s2::`, not `s2`.  Otherwise the downstream imported target becomes `s2s2` instead of `s2::s2`, which is the actual convention.  Sorry, this was a result of my inexperience with the details of building these configs as opposed to consuming them.
Second, I failed to include put the absl dependency into the exported exported CMake config for downstream projects.  This is necessary because absl is part of the public interface for s2, and thus will be a dependency of any downstream project.  The VCPKG dependency mechanism already ensures that absl will be built and installed if s2geometry is requested, but this change is requires to avoid downstream packages having …
> Fix vs2019 & namespace for install targets

- src/s2/s2builder_graph.h
- src/s2/s2shape_index.h
https://en.cppreference.com/w/cpp/iterator/iterator is deprecated in c++17 and forward
> Avoid deprecated `std::iterator`

- src/s2/util/endian/endian.h
- src/s2/util/gtl/compact_array.h
PR https://github.com/google/s2geometry/pull/367 forgot to adjust a few types which are under the `IS_BIG_ENDIAN` define.
> Fix big endian build

- src/s2/s2polyline.cc
- src/s2/s2polyline.h
The code is structured like this:
```
class S2Polyline {
class OwningShape {
std::unique_ptr<S2Polyline> owned_polyline_;
};
};
```
libcxx 16 complains that S2Polyline is not defined at the point where
the dtor of the unique_ptr is called (which is OwningShape's implicitly
declared default destructor in the same header file) (also see [0]).
As a remedy, declare OwningShape's destructor in the source file where
the full declaration of S2Polyline is visible.
[0] https://stackoverflow.com/a/34073093/22422288)
> Fix build with libcxx16

- CMakeLists.txt
This will help handling s2 versions in downstream cmake projects.
`COMPATIBILITY SameMinorVersion` seems safer than `SameMajorVersion` or `AnyNewerVersion` (cf. some changes like S2ShapeIndex::CellRelation => S2CellRelation from v0.10 to v0.11).
> Create and install a cmake config version file

- CMakeLists.txt
The "Development" component of  Python3 needs more files than we care about (e.g. `libpython3.xx.so`). 
However when compiling a module, we only need part of the development files, (e.g. the headers).
To support this distinction, [cmake added `Development.Modules` in 3.18](https://cmake.org/cmake/help/latest/module/FindPython3.html) so that this will work in more environments (e.g. docker image `quay.io/pypa/manylinux_2_28_x86_64`)
> Update CMakeLists.txt for python bindings

- src/s2/s2loop_measures_test.cc
This fails and needs more investigation.
See #395.
Disable it so we can have clean presubmit checks.
> s2loop_measures_test: Disable GetSignedArea on arm64 macOS

- README.md
Now abseil and gtest may be installed using MacPorts.
> README.md: Update macOS instructions

- CMakeLists.txt
Closes #398
Mac seems to use dynamic linking more for making modules than Linux and Windows do. Thus the common python symbols were missing and it requires `libpython3.13.dylib` for these symbols. If this is a different in the mac "Framework" then cmake should probably include that for the `Development.Module` component. But this is a workaround in the meantime while we wait for any upstream fixes.
> Fix macos build error

- .github/workflows/build.yml
- .github/workflows/test.yml
run `cmake` and `make install` in GitHub Actions to test the build
> automatically build library with `cmake` and test with `ctest`

- src/s2/s2loop_measures_test.cc
This was previously skipped only for AArch64 macOS.
https://github.com/google/s2geometry/blob/master/src/s2/s2loop_measures_test.cc#L256
The test fails for x86-64 macOS as well.  
https://github.com/google/s2geometry/issues/395#issuecomment-2629120303
Disable for `__APPLE__`.
> Skip GetSignedArea.ErrorAccumulation test on macOS

- .gitignore
- src/MODULE.bazel
Context: https://github.com/bazelbuild/bazel/issues/24426
Fixes `bazel mod deps`.
cc @romanoid-openai
> Fixed where `cc_configure_extension` comes from.

- src/s2/s1angle.h
S1Angle.Trigonometry fails on Ubuntu 22.  Disable for all glibc targets until this can be narrowed down further.
```
/home/runner/work/s2geometry/s2geometry/src/s2/s1angle_test.cc:139: Failure
Expected equality of these values:
sin_cos.cos
Which is: -0.2[58](https://github.com/google/s2geometry/actions/runs/13603572823/job/38032416706?pr=412#step:8:59)81904510251996
cos(angle)
Which is: -0.25881904510251991
[  FAILED  ] S1Angle.Trigonometry (0 ms)
```
> S1Angle::SinCos: Disable sincos for glibc

- .github/workflows/build.yml
- .github/workflows/test.yml
Disable test/macos-latest due to timeouts.
https://github.com/google/s2geometry/issues/409
Enable ubuntu-22.
> workflows: Disable macos and enable ubuntu-22

- CMakeLists.txt
Add `add_compile_options(-fsized-deallocation)` to non-MSVC compiler options.
`base/port.h` uses sized deallocation, which should be enabled by default for C++14 and later.  There appears to be a bug with clang < 19 causing this not to be enabled.
https://github.com/google/s2geometry/issues/411#issuecomment-2726949607 This can be removed when clang19 is the minimum supported version.
Fixes #411.
> CMakeLists: Work around clang sized dealloc bug

- .github/workflows/build.yml
- .github/workflows/test.yml
Bump zacharyburnett/setup-abseil-cpp version to hash that includes new actions/cache version from
https://github.com/zacharyburnett/setup-abseil-cpp/pull/5.
There is no corresponding release.
Fixes #423.
> workflows: Bump setup-abseil-cpp version

- src/MODULE.bazel
Refresh MODULE.bazel with newer versions of some dependencies.
boringssl was a year out of date and no longer available to pull in. The other two are just a minor version bumps.
Fixes #426
> MODULE.bazel: Update

- .github/workflows/build.yml
- .github/workflows/test.yml
This was disabled for Linux because the jobs were getting cancelled.  It is far too slow building sequentially (8 minutes instead of 1 minutes), so try re-enabling it.
> test.yml: build with --parallel

- .github/workflows/test.yml
Previously, the tests were not running in parallel.
> test.yml: Run with ctest --parallel

- src/s2/s2cell_id.cc
This is meant to work around the situation when `absl::bit_width` is `unsigned long`.
```
error: no matching function for call to 'max'
[build]   return max(61 - absl::bit_width(bits), -1) >> 1;
[build]          ^~~
[build] /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/algorithmfwd.h:407:5: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('unsigned long' vs. 'int')
```
ref https://github.com/abseil/abseil-cpp/issues/1890
ref https://github.com/google/s2geometry/pull/421#discussion_r2095372420
System: Debian 12
Compiler: Clang-15
> GetCommonAncestorLevel: work around bit_width return type bug

- .github/workflows/bazel.yml
Based on https://github.com/bazel-contrib/setup-bazel?tab=readme-ov-file#usage
and build.yml.
This is slow for some reason, taking ~10 minutes, whereas `bazel test ...` takes 1.5 minutes for me.
Fixes #428
> bazel.yml: Add Bazel workflow
